### ISSUE TITLE
*.bat scripts do not work for Mac/Linux

### ISSUE THREAD

**Issue by mschroen** [mschroen/science.md#2]
Due to the fact that operating systems interpret `.bat` scripts differently, currently the following files only work on Windows:

- `make.bat`
- `release/diff.bat`
- `release/release.bat`
- `plan/Gantt2html.bat`

The problem basically boils down to (1) special newline characters, (2) special escaping characters, and (3) special `sed` syntax.  Those are different from system to system (e.g., character `^` on Windows).

Mac and Linux users are asked to resolve this issue. Thanks!

**Comment by JF-soft** [comment]
Hey, I discovered your project today, I made some simple scripts in python to replace some .bat files (Gantt2html, pdf2png and protocol2beamer), I haven't implemented the ones on release yet.  I don't know much about sharing code in github but we can figure it out if you're interested. I also modified pandoc.tex template because pandoc and latex were complaining about some csl missing feature in it. I'm running the build in Manjaro linux.

**Comment by mschroen** [comment]
Thanks JF-soft, your contribution would be appreciated. Please open a new branch, commit your changes to it, and push to GitHub. I will test your new implementation and merge with master.

**Comment by mschroen** [comment]
Looks like @JF-soft solved it via pull request #7. *Science.md* is now linux-aware :-)

**Comment by JF-soft** [comment]
@mschroen if you need more help to support linux, please let me know, I will try to help you as best as I can. Thanks for sharing this project.
